steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 
    'deploy', 
    '--entry-point', 
    'helloWorld', 
    '--runtime', 'nodejs6', 
    '--trigger-topic', 'helloWorld',
    '--project', 'photo-storage-test-40dab' 
  ]
  dir: ''