steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 'deploy', 'resizeImage',
    '--runtime', 'nodejs8',
    '--trigger-event', 'google.storage.object.finalize'
  ]
  dir: ''